### ISSUE TITLE
Jetty fails to start at boot

### ISSUE THREAD

**Issue by dstepe** [MiamiOH/puppet-shibboleth_idp#7]
The systemd setup does not seem to be correct.

**Comment by edestecd** [comment]
http://shibboleth.net/pipermail/users/2015-July/023251.html

**Comment by edestecd** [comment]
This one seems to be what we are using.
https://github.com/allette/jetty-systemd-unit

It has a jetty.conf. Are we doing that?

**Comment by edestecd** [comment]
https://gist.github.com/canariecaf/0fdd6db9e4f294afca79

**Comment by edestecd** [comment]
http://www.vleo.net/docs/projects/jetty/jetty@.service
