### ISSUE TITLE
PKCS12 file name is missing in idp_jetty/start.d/ssl.ini

### ISSUE THREAD

**Issue by dstepe** [MiamiOH/puppet-shibboleth_idp#9]
The cert file name should be in the following line. The default is supposed to be $::fqdn

```
jetty.sslContext.keyStorePath=/etc/ssl/certs/.p12
```

**Comment by edestecd** [comment]
What class is this set in?

**Comment by dstepe** [comment]
It turns out this issue was actually in the profile calling this module. It's been addressed there.
